name: Tests Unitaires

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: docker

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn

    - name: Run tests
      if: ${{ github.event_name == 'pull_request' }}
      run: yarn test

